version: '3.8'

services:
  pharma-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8090:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://pharma_user:pharma_pass@postgres:5432/pharma_db
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: pharma_user
      POSTGRES_PASSWORD: pharma_pass
      POSTGRES_DB: pharma_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: