# ============================================================================
# 🏥 SRE: Service Level Objectives for Pharmaceutical Manufacturing
# ============================================================================
# SLOs for FDA-compliant pharmaceutical manufacturing systems
# Higher availability requirements due to patient safety implications

apiVersion: v1
kind: ConfigMap
metadata:
  name: pharma-manufacturing-slos
  namespace: pharma-manufacturing
  labels:
    app: pharma-manufacturing
    component: sre-slos
    # 🏷️ SRE COMPONENT: Service Level Objectives
data:
  # ==========================================================================
  # 📊 SRE: Service Level Indicators (SLIs) - What We Measure
  # ==========================================================================
  
  # Availability SLI: Percentage of successful requests
  availability_sli: |
    # Manufacturing systems must maintain high availability
    sum(rate(http_requests_total{job="pharma-manufacturing",code=~"2.."}[5m])) /
    sum(rate(http_requests_total{job="pharma-manufacturing"}[5m])) * 100

  # Latency SLI: 95th percentile response time
  latency_sli_p95: |
    # Manufacturing processes can tolerate slightly higher latency
    histogram_quantile(0.95, 
      sum(rate(http_request_duration_seconds_bucket{job="pharma-manufacturing"}[5m])) by (le)
    ) * 1000

  # Data Integrity SLI: Percentage of data validation successes
  data_integrity_sli: |
    # Critical for FDA compliance - all data must be valid
    sum(rate(data_validation_success_total{job="pharma-manufacturing"}[5m])) /
    sum(rate(data_validation_total{job="pharma-manufacturing"}[5m])) * 100

  # Batch Success Rate SLI: Percentage of successful manufacturing batches
  batch_success_sli: |
    # Manufacturing efficiency indicator
    sum(rate(manufacturing_batch_success_total[5m])) /
    sum(rate(manufacturing_batch_total[5m])) * 100

  # ==========================================================================
  # 🎯 SRE: Service Level Objectives (SLOs) - What We Promise
  # ==========================================================================
  
  slo_targets: |
    # 🏥 PHARMA MANUFACTURING SLOs (Patient safety focus)
    
    availability_target: 99.95%   # 21.9 minutes downtime/month
    latency_p95_target: 100ms     # Reasonable for manufacturing workflows
    data_integrity_target: 99.99% # FDA requires near-perfect data integrity
    batch_success_target: 98%     # Manufacturing efficiency target
    
    # 📅 SLO Measurement Windows
    measurement_window: 30d       # Monthly compliance reporting
    alerting_window: 5m          # Real-time monitoring
    
    # 🚨 SLO Alerting Thresholds (Conservative for safety)
    availability_alert: 99.9%    # Earlier warning for critical systems
    latency_alert: 200ms         # 2x target latency
    data_integrity_alert: 99.95% # Any data integrity issues are serious
    batch_success_alert: 95%     # Manufacturing efficiency concern

  # ==========================================================================
  # 💊 SRE: Error Budget Configuration
  # ==========================================================================
  
  error_budget_config: |
    # 📊 ERROR BUDGET CALCULATION
    # Conservative budgets due to patient safety implications
    
    # Monthly Error Budget Allowances:
    availability_budget: 0.05%    # 99.95% SLO = 0.05% error budget
    latency_budget: 5%           # 5% of requests can exceed 100ms
    data_integrity_budget: 0.01% # 99.99% SLO = 0.01% error budget
    
    # 🚦 Error Budget Burn Rate Alerts
    fast_burn_rate: 28.8         # Burn 30d budget in 1h (very aggressive)
    slow_burn_rate: 1.0          # Burn 30d budget in 30d
    
    # 📈 Error Budget Policies (Strict for pharma)
    budget_exhausted_action: "freeze_all_changes"
    budget_warning_threshold: 50%  # Earlier warning
    budget_critical_threshold: 75% # Earlier critical alert

  # ==========================================================================
  # 🧪 SRE: Manufacturing-Specific SLIs
  # ==========================================================================
  
  manufacturing_slis: |
    # 🌡️ Environmental Monitoring SLIs
    temperature_compliance_sli: |
      # Percentage of time temperature is within acceptable range
      sum(rate(temperature_in_range_total[5m])) /
      sum(rate(temperature_readings_total[5m])) * 100
    
    # 🔬 Equipment Uptime SLI
    equipment_uptime_sli: |
      # Percentage of time critical equipment is operational
      sum(rate(equipment_operational_total[5m])) /
      sum(rate(equipment_status_total[5m])) * 100
    
    # 📋 Audit Trail Completeness SLI
    audit_completeness_sli: |
      # FDA requires 100% audit trail coverage
      sum(rate(audit_events_recorded_total[5m])) /
      sum(rate(audit_events_generated_total[5m])) * 100

  # ==========================================================================
  # 📋 SRE: Business Context & Compliance Justification
  # ==========================================================================
  
  business_context: |
    # 🏥 WHY THESE SLO TARGETS?
    
    Availability (99.95%):
    - Patient safety depends on system availability
    - FDA requires high uptime for critical manufacturing systems
    - Production batches cannot be interrupted without significant loss
    - 21.9 minutes downtime/month allows for planned maintenance
    
    Latency (100ms p95):
    - Manufacturing workflows less time-sensitive than trading
    - Reasonable response time for complex pharmaceutical processes
    - Allows for data validation and compliance checks
    
    Data Integrity (99.99%):
    - FDA 21 CFR Part 11 requires near-perfect data integrity
    - Any data corruption can invalidate entire production batches
    - Patient safety depends on accurate manufacturing data
    - Regulatory fines for data integrity violations are severe
    
    Batch Success Rate (98%):
    - Manufacturing efficiency directly impacts patient access
    - Failed batches represent significant financial loss
    - Industry benchmark for pharmaceutical manufacturing
    - Allows for continuous process improvement

  # ==========================================================================
  # 🏛️ SRE: Regulatory Compliance Mapping
  # ==========================================================================
  
  regulatory_mapping: |
    # 📜 FDA 21 CFR Part 11 SLO Alignment:
    
    Electronic Records:
    - Data integrity SLI ensures record accuracy and completeness
    - Audit trail completeness SLI tracks all system interactions
    - Availability SLO ensures records are accessible when needed
    
    Electronic Signatures:
    - Authentication system availability included in overall SLO
    - Signature validation latency tracked separately
    
    Good Manufacturing Practice (GMP):
    - Environmental monitoring SLIs ensure compliance conditions
    - Equipment uptime SLIs track critical manufacturing capability
    - Batch success rate aligns with GMP quality objectives

---
# 📝 SRE Implementation Notes:
# - Manufacturing SLOs are more conservative due to patient safety
# - Multiple SLIs required to cover complex manufacturing processes  
# - Error budgets guide change management in regulated environment
# - SLO violations may require regulatory incident reporting