# Prometheus Configuration for Trading System
# Development environment monitoring setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'
    cluster: 'trading-local'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Trading application
  - job_name: 'trading-app'
    static_configs:
      - targets: ['app:9090']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 5s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Trading application health checks
  - job_name: 'trading-health'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/health/summary'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Custom business metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics/business'
    scrape_interval: 30s

  # Compliance metrics
  - job_name: 'compliance-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics/compliance'
    scrape_interval: 60s

  # Performance metrics
  - job_name: 'performance-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics/performance'
    scrape_interval: 10s

# Remote write configuration for long-term storage
remote_write:
  - url: "http://mimir:9009/api/v1/push"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 7d
    retention.size: 1GB