# Prometheus Configuration for Trading System
# Staging environment monitoring setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'staging'
    cluster: 'trading-staging'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Trading application
  - job_name: 'trading-app'
    static_configs:
      - targets: ['app:9090']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 5s
    scrape_timeout: 10s

  # Health checks
  - job_name: 'trading-health'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/health/summary'
    scrape_interval: 10s

  # Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 15s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 7d
    retention.size: 2GB