version: '3.8'

services:
  # Frontend - serves all dashboards
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  # Finance Trading Backend
  finance-app:
    build:
      context: ./apps/finance-trading
      dockerfile: Dockerfile.bulletproof
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - PORT=8080
    networks:
      - app-network
    restart: unless-stopped

  # Pharma Manufacturing Backend
  pharma-app:
    build:
      context: ./apps/pharma-manufacturing
      dockerfile: Dockerfile.bulletproof
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge