# ============================================================================
# 🎯 SRE: Service Level Objectives for Finance Trading System
# ============================================================================
# These SLOs define what "good" means for our trading platform
# Used for error budget calculations and reliability targets

apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-trading-slos
  namespace: finance-trading
  labels:
    app: finance-trading
    component: sre-slos
    # 🏷️ SRE COMPONENT: Service Level Objectives
data:
  # ==========================================================================
  # 📊 SRE: Service Level Indicators (SLIs) - What We Measure
  # ==========================================================================
  
  # Availability SLI: Percentage of successful requests
  availability_sli: |
    # Successful requests / Total requests
    # HTTP 2xx responses are considered successful
    sum(rate(http_requests_total{job="finance-trading",code=~"2.."}[5m])) /
    sum(rate(http_requests_total{job="finance-trading"}[5m])) * 100

  # Latency SLI: 95th percentile response time
  latency_sli_p95: |
    # 95% of requests should complete within target time
    histogram_quantile(0.95, 
      sum(rate(http_request_duration_seconds_bucket{job="finance-trading"}[5m])) by (le)
    ) * 1000  # Convert to milliseconds

  # Error Rate SLI: Percentage of failed requests
  error_rate_sli: |
    # Failed requests / Total requests
    # HTTP 4xx, 5xx responses are considered errors
    sum(rate(http_requests_total{job="finance-trading",code=~"[45].."}[5m])) /
    sum(rate(http_requests_total{job="finance-trading"}[5m])) * 100

  # Throughput SLI: Requests per second
  throughput_sli: |
    # Total requests per second the system is handling
    sum(rate(http_requests_total{job="finance-trading"}[5m]))

  # ==========================================================================
  # 🎯 SRE: Service Level Objectives (SLOs) - What We Promise
  # ==========================================================================
  
  # Financial trading requires ultra-high reliability
  slo_targets: |
    # 🏦 FINANCE TRADING SLOs (Stringent requirements for financial systems)
    
    availability_target: 99.9%    # 43.8 minutes downtime/month
    latency_p95_target: 50ms      # Ultra-low latency for trading
    error_rate_target: 0.1%       # Very low error tolerance
    throughput_target: 1000rps    # Handle high-frequency trading
    
    # 📅 SLO Measurement Windows
    measurement_window: 30d       # Monthly SLO evaluation
    alerting_window: 5m          # Real-time SLO monitoring
    
    # 🚨 SLO Alerting Thresholds
    availability_alert: 99.5%    # Alert at 2x error rate
    latency_alert: 100ms         # Alert at 2x target latency
    error_rate_alert: 0.2%       # Alert at 2x error rate

  # ==========================================================================
  # 💰 SRE: Error Budget Configuration
  # ==========================================================================
  
  error_budget_config: |
    # 📊 ERROR BUDGET CALCULATION
    # Error Budget = (100% - SLO) × Total Requests
    
    # Monthly Error Budget Allowances:
    availability_budget: 0.1%     # 99.9% SLO = 0.1% error budget
    latency_budget: 5%           # 5% of requests can exceed 50ms
    
    # 🚦 Error Budget Burn Rate Alerts
    fast_burn_rate: 14.4         # Burn 30d budget in 2h (budget/month * 30*24/2)
    slow_burn_rate: 1.0          # Burn 30d budget in 30d (budget/month)
    
    # 📈 Error Budget Policies
    budget_exhausted_action: "freeze_deployments"
    budget_warning_threshold: 75%
    budget_critical_threshold: 90%

  # ==========================================================================
  # 📋 SRE: Business Context & Justification
  # ==========================================================================
  
  business_context: |
    # 🏦 WHY THESE SLO TARGETS?
    
    Availability (99.9%):
    - Trading systems must be available during market hours
    - 43.8 minutes downtime/month acceptable for maintenance
    - Regulatory requirement for financial system uptime
    
    Latency (50ms p95):
    - High-frequency trading requires ultra-low latency
    - Market opportunities disappear in milliseconds
    - Competitive advantage depends on speed
    
    Error Rate (0.1%):
    - Financial transactions must be highly reliable
    - Errors can result in significant monetary loss
    - Regulatory compliance requires low error rates
    
    Throughput (1000 RPS):
    - Support peak trading volumes during market volatility
    - Handle multiple concurrent trading strategies
    - Scale for institutional trading clients

---
# 📝 SRE Implementation Notes:
# - These SLOs are monitored via Prometheus metrics
# - Grafana dashboards visualize SLO compliance
# - Alertmanager sends notifications on SLO violations
# - Error budgets guide deployment decisions