apiVersion: v1
kind: Service
metadata:
  name: finance-trading-service
  namespace: finance-prod
  labels:
    app: finance-trading
    tier: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: finance-trading
    version: v1
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: finance-trading-headless
  namespace: finance-prod
  labels:
    app: finance-trading
    tier: production
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: finance-trading
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: finance-trading-blue
  namespace: finance-prod
  labels:
    app: finance-trading
    tier: production
    deployment-color: blue
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    finance.trading/deployment-strategy: "blue-green"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: finance-trading
    version: v1
    deployment-color: blue
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: finance-trading-green
  namespace: finance-prod
  labels:
    app: finance-trading
    tier: production
    deployment-color: green
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    finance.trading/deployment-strategy: "blue-green"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: finance-trading
    version: v1
    deployment-color: green
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: finance-trading-canary
  namespace: finance-prod
  labels:
    app: finance-trading
    tier: production
    deployment-type: canary
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    finance.trading/canary-weight: "5"
    finance.trading/success-rate-threshold: "99.99"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: finance-trading
    version: v2
    deployment-type: canary
  externalTrafficPolicy: Local
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: finance-trading-pdb
  namespace: finance-prod
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app: finance-trading
      tier: production
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: finance-trading-hpa
  namespace: finance-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finance-trading-app
  minReplicas: 6
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: trading_latency_p99
      target:
        type: AverageValue
        averageValue: "40m"
  - type: Pods
    pods:
      metric:
        name: trading_success_rate
      target:
        type: AverageValue
        averageValue: "99.99"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min