apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pharma-manufacturing-monitor
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    tier: production
    compliance: fda-21cfr11
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: pharma-manufacturing
  endpoints:
  - port: metrics
    interval: 10s
    path: /metrics
    honorLabels: true
    scrapeTimeout: 8s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'pharma_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'manufacturing_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'sensor_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'batch_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'audit_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'http_request_duration_seconds.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'http_requests_total.*'
      action: keep
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pharma-manufacturing-alerts
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    tier: production
    compliance: fda-21cfr11
    prometheus: kube-prometheus
spec:
  groups:
  - name: pharma-manufacturing.efficiency
    interval: 15s
    rules:
    - alert: ManufacturingEfficiencyLow
      expr: manufacturing_line_efficiency_percent{job="pharma-manufacturing"} < 98
      for: 60s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: fda-violation
      annotations:
        summary: "Manufacturing line efficiency below 98%"
        description: "Manufacturing line {{ $labels.line_id }} efficiency is {{ $value }}%, which is below the 98% minimum requirement"
        runbook_url: "https://runbooks.pharma.example.com/manufacturing-efficiency"
        remediation: "Check equipment status, sensor readings, and batch quality"
        
    - alert: ManufacturingLineStopped
      expr: manufacturing_line_status{job="pharma-manufacturing"} == 0
      for: 30s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: production-halt
      annotations:
        summary: "Manufacturing line stopped"
        description: "Manufacturing line {{ $labels.line_id }} has stopped production"
        runbook_url: "https://runbooks.pharma.example.com/line-stopped"
        remediation: "Immediate investigation required - check equipment and sensor status"
        
  - name: pharma-manufacturing.sensors
    interval: 5s
    rules:
    - alert: TemperatureSensorOutOfRange
      expr: |
        (sensor_temperature_celsius{job="pharma-manufacturing", critical="true"} < 18.0) or
        (sensor_temperature_celsius{job="pharma-manufacturing", critical="true"} > 25.0)
      for: 30s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: gmp-violation
      annotations:
        summary: "Critical temperature sensor out of range"
        description: "Temperature sensor {{ $labels.sensor_id }} reading {{ $value }}°C is outside acceptable range (18-25°C)"
        runbook_url: "https://runbooks.pharma.example.com/temperature-alarm"
        remediation: "Immediately check HVAC system and product integrity"
        
    - alert: PressureSensorOutOfRange
      expr: |
        (sensor_pressure_bar{job="pharma-manufacturing", critical="true"} < 0.8) or
        (sensor_pressure_bar{job="pharma-manufacturing", critical="true"} > 2.5)
      for: 30s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: gmp-violation
      annotations:
        summary: "Critical pressure sensor out of range"
        description: "Pressure sensor {{ $labels.sensor_id }} reading {{ $value }} bar is outside acceptable range (0.8-2.5 bar)"
        runbook_url: "https://runbooks.pharma.example.com/pressure-alarm"
        remediation: "Check pressure systems and reactor integrity"
        
    - alert: SensorValidationFailed
      expr: sensor_validation_success_rate{job="pharma-manufacturing"} < 99.5
      for: 60s
      labels:
        severity: warning
        service: pharma-manufacturing
        business_impact: medium
        compliance: validation-required
      annotations:
        summary: "Sensor validation success rate low"
        description: "Sensor validation success rate is {{ $value }}%, below 99.5% threshold"
        runbook_url: "https://runbooks.pharma.example.com/sensor-validation"
        remediation: "Review sensor calibration and validation procedures"
        
  - name: pharma-manufacturing.batches
    interval: 30s
    rules:
    - alert: BatchIntegrityFailure
      expr: batch_integrity_score{job="pharma-manufacturing"} < 100
      for: 0s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: fda-violation
      annotations:
        summary: "Batch integrity check failed"
        description: "Batch {{ $labels.batch_id }} integrity score is {{ $value }}%, indicating data corruption or validation failure"
        runbook_url: "https://runbooks.pharma.example.com/batch-integrity"
        remediation: "Immediate batch isolation and investigation required"
        
    - alert: BatchProcessingDelay
      expr: batch_processing_duration_seconds{job="pharma-manufacturing"} > 14400  # 4 hours
      for: 300s
      labels:
        severity: warning
        service: pharma-manufacturing
        business_impact: medium
        compliance: schedule-deviation
      annotations:
        summary: "Batch processing delayed"
        description: "Batch {{ $labels.batch_id }} has been processing for {{ $value }} seconds, exceeding normal duration"
        runbook_url: "https://runbooks.pharma.example.com/batch-delay"
        remediation: "Review batch processing parameters and equipment status"
        
  - name: pharma-manufacturing.compliance
    interval: 10s
    rules:
    - alert: AuditTrailCorruption
      expr: audit_trail_integrity_check{job="pharma-manufacturing"} == 0
      for: 0s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: fda-violation
      annotations:
        summary: "Audit trail integrity check failed"
        description: "Audit trail integrity check failed, indicating potential data corruption"
        runbook_url: "https://runbooks.pharma.example.com/audit-trail"
        remediation: "Immediate investigation required - contact compliance team"
        
    - alert: DigitalSignatureValidationFailed
      expr: digital_signature_validation_failures{job="pharma-manufacturing"} > 0
      for: 0s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: fda-violation
      annotations:
        summary: "Digital signature validation failed"
        description: "Digital signature validation failed for {{ $value }} records"
        runbook_url: "https://runbooks.pharma.example.com/digital-signature"
        remediation: "Investigate signature validation process and user credentials"
        
    - alert: DeploymentDuringProduction
      expr: pharma_deployment_active{job="pharma-manufacturing"} == 1 and on() pharma_production_active{job="pharma-manufacturing"} == 1
      for: 0s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: gmp-violation
      annotations:
        summary: "Deployment attempted during active production"
        description: "A deployment was attempted while production line is active"
        runbook_url: "https://runbooks.pharma.example.com/production-deployment"
        remediation: "Halt deployment and investigate change control process"
        
  - name: pharma-manufacturing.system
    interval: 30s
    rules:
    - alert: PharmaPodsDown
      expr: up{job="pharma-manufacturing"} == 0
      for: 60s
      labels:
        severity: critical
        service: pharma-manufacturing
        business_impact: high
        compliance: system-availability
      annotations:
        summary: "Pharma manufacturing pod is down"
        description: "Manufacturing pod {{ $labels.pod }} is not responding"
        runbook_url: "https://runbooks.pharma.example.com/pod-down"
        remediation: "Check pod status and restart if necessary"
        
    - alert: PharmaMemoryUsageHigh
      expr: (container_memory_usage_bytes{pod=~"pharma-manufacturing-.*"} / container_spec_memory_limit_bytes) * 100 > 85
      for: 300s
      labels:
        severity: warning
        service: pharma-manufacturing
        business_impact: medium
        compliance: system-performance
      annotations:
        summary: "Pharma manufacturing pod memory usage high"
        description: "Pod {{ $labels.pod }} memory usage is {{ $value }}%"
        runbook_url: "https://runbooks.pharma.example.com/memory-usage"
        remediation: "Review memory allocation and consider scaling"
        
    - alert: PharmaCPUUsageHigh
      expr: (rate(container_cpu_usage_seconds_total{pod=~"pharma-manufacturing-.*"}[5m]) / container_spec_cpu_quota * container_spec_cpu_period) * 100 > 85
      for: 300s
      labels:
        severity: warning
        service: pharma-manufacturing
        business_impact: medium
        compliance: system-performance
      annotations:
        summary: "Pharma manufacturing pod CPU usage high"
        description: "Pod {{ $labels.pod }} CPU usage is {{ $value }}%"
        runbook_url: "https://runbooks.pharma.example.com/cpu-usage"
        remediation: "Review CPU allocation and consider scaling"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pharma-dashboard-config
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    compliance: fda-21cfr11
data:
  dashboard.json: |
    {
      "dashboard": {
        "title": "Pharma Manufacturing Control System - FDA Compliant",
        "tags": ["pharma", "manufacturing", "fda", "gmp", "production"],
        "timezone": "UTC",
        "refresh": "10s",
        "time": {
          "from": "now-4h",
          "to": "now"
        },
        "templating": {
          "list": [
            {
              "name": "manufacturing_line",
              "query": "label_values(manufacturing_line_efficiency_percent, line_id)",
              "current": {
                "value": "LINE-001-PHARMA-PROD"
              }
            },
            {
              "name": "batch_id",
              "query": "label_values(batch_integrity_score, batch_id)",
              "current": {
                "value": "All"
              }
            }
          ]
        },
        "panels": [
          {
            "title": "Manufacturing Line Efficiency",
            "type": "stat",
            "targets": [
              {
                "expr": "manufacturing_line_efficiency_percent{line_id=\"$manufacturing_line\"}",
                "legendFormat": "Efficiency %"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": 0},
                    {"color": "yellow", "value": 98},
                    {"color": "green", "value": 99}
                  ]
                },
                "unit": "percent",
                "min": 95,
                "max": 100
              }
            }
          },
          {
            "title": "Critical Temperature Sensors",
            "type": "graph",
            "targets": [
              {
                "expr": "sensor_temperature_celsius{critical=\"true\"}",
                "legendFormat": "{{sensor_id}} - {{location}}"
              }
            ],
            "yAxes": [
              {
                "min": 15,
                "max": 30,
                "unit": "celsius"
              }
            ],
            "alert": {
              "conditions": [
                {
                  "query": {
                    "queryType": "",
                    "refId": "A"
                  },
                  "reducer": {
                    "params": [],
                    "type": "last"
                  },
                  "evaluator": {
                    "params": [18, 25],
                    "type": "outside_range"
                  }
                }
              ],
              "executionErrorState": "alerting",
              "for": "30s",
              "frequency": "5s",
              "handler": 1,
              "name": "Temperature Out of Range",
              "noDataState": "no_data",
              "notifications": []
            }
          },
          {
            "title": "Critical Pressure Sensors",
            "type": "graph",
            "targets": [
              {
                "expr": "sensor_pressure_bar{critical=\"true\"}",
                "legendFormat": "{{sensor_id}} - {{location}}"
              }
            ],
            "yAxes": [
              {
                "min": 0,
                "max": 3,
                "unit": "bar"
              }
            ]
          },
          {
            "title": "Batch Integrity Scores",
            "type": "table",
            "targets": [
              {
                "expr": "batch_integrity_score",
                "legendFormat": "{{batch_id}}"
              }
            ],
            "transformations": [
              {
                "id": "organize",
                "options": {
                  "excludeByName": {},
                  "indexByName": {},
                  "renameByName": {
                    "batch_id": "Batch ID",
                    "Value": "Integrity Score"
                  }
                }
              }
            ]
          },
          {
            "title": "Audit Trail Status",
            "type": "stat",
            "targets": [
              {
                "expr": "audit_trail_integrity_check",
                "legendFormat": "Audit Trail Integrity"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": 0},
                    {"color": "green", "value": 1}
                  ]
                },
                "mappings": [
                  {
                    "options": {
                      "0": {
                        "text": "FAILED"
                      },
                      "1": {
                        "text": "PASSED"
                      }
                    },
                    "type": "value"
                  }
                ]
              }
            }
          },
          {
            "title": "Digital Signature Validation",
            "type": "stat",
            "targets": [
              {
                "expr": "digital_signature_validation_failures",
                "legendFormat": "Validation Failures"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": 0},
                    {"color": "red", "value": 1}
                  ]
                },
                "unit": "short"
              }
            }
          },
          {
            "title": "System Resource Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "(container_memory_usage_bytes{pod=~\"pharma-manufacturing-.*\"} / container_spec_memory_limit_bytes) * 100",
                "legendFormat": "Memory % - {{pod}}"
              },
              {
                "expr": "(rate(container_cpu_usage_seconds_total{pod=~\"pharma-manufacturing-.*\"}[5m]) / container_spec_cpu_quota * container_spec_cpu_period) * 100",
                "legendFormat": "CPU % - {{pod}}"
              }
            ],
            "yAxes": [
              {
                "min": 0,
                "max": 100,
                "unit": "percent"
              }
            ]
          }
        ]
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-config
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    compliance: fda-21cfr11
data:
  audit-policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    rules:
    - level: Metadata
      namespaces: ["pharma-prod"]
      verbs: ["get", "list", "create", "update", "patch", "delete"]
      resources:
      - group: ""
        resources: ["pods", "services", "configmaps", "secrets"]
      - group: "apps"
        resources: ["deployments", "replicasets"]
      - group: "networking.k8s.io"
        resources: ["ingresses"]
      omitStages:
      - RequestReceived
    - level: Request
      namespaces: ["pharma-prod"]
      verbs: ["create", "update", "patch", "delete"]
      resources:
      - group: ""
        resources: ["persistentvolumeclaims"]
      - group: "apps"
        resources: ["deployments"]
      omitStages:
      - RequestReceived
      - ResponseStarted
  retention-policy.yaml: |
    # FDA 21 CFR Part 11 Retention Policy
    retention_requirements:
      audit_logs:
        retention_years: 7
        backup_frequency: "daily"
        archival_location: "s3://pharma-audit-archive"
        encryption_required: true
      batch_records:
        retention_years: 7
        backup_frequency: "hourly"
        archival_location: "s3://pharma-batch-archive"
        encryption_required: true
      system_logs:
        retention_years: 3
        backup_frequency: "daily"
        archival_location: "s3://pharma-system-logs"
        encryption_required: true
      digital_signatures:
        retention_years: 7
        backup_frequency: "daily"
        archival_location: "s3://pharma-signatures"
        encryption_required: true
        verification_required: true