apiVersion: v1
kind: Service
metadata:
  name: pharma-manufacturing-service
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    tier: production
    compliance: fda-21cfr11
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    pharma.fda/audit-logging: "enabled"
    pharma.fda/access-control: "required"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: scada
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: pharma-manufacturing
    version: v1
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: pharma-manufacturing-headless
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    tier: production
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: sensor-api
    port: 8083
    targetPort: 8083
    protocol: TCP
  - name: batch-api
    port: 8084
    targetPort: 8084
    protocol: TCP
  - name: audit-api
    port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: pharma-manufacturing
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: pharma-sensor-service
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    component: sensor-monitoring
    compliance: fda-21cfr11
  annotations:
    pharma.fda/sensor-validation: "required"
    pharma.fda/critical-system: "true"
spec:
  type: ClusterIP
  ports:
  - name: sensor-api
    port: 8083
    targetPort: 8083
    protocol: TCP
  - name: sensor-metrics
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: pharma-manufacturing
    component: sensor-monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: pharma-batch-service
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    component: batch-integrity
    compliance: fda-21cfr11
  annotations:
    pharma.fda/batch-validation: "required"
    pharma.fda/data-integrity: "critical"
spec:
  type: ClusterIP
  ports:
  - name: batch-api
    port: 8084
    targetPort: 8084
    protocol: TCP
  - name: batch-metrics
    port: 9094
    targetPort: 9094
    protocol: TCP
  selector:
    app: pharma-manufacturing
    component: batch-integrity
---
apiVersion: v1
kind: Service
metadata:
  name: pharma-audit-service
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    component: audit-logging
    compliance: fda-21cfr11
  annotations:
    pharma.fda/audit-trail: "required"
    pharma.fda/digital-signatures: "required"
spec:
  type: ClusterIP
  ports:
  - name: audit-api
    port: 8085
    targetPort: 8085
    protocol: TCP
  - name: audit-metrics
    port: 9095
    targetPort: 9095
    protocol: TCP
  selector:
    app: pharma-manufacturing
    component: audit-logging
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pharma-manufacturing-pdb
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    compliance: fda-21cfr11
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: pharma-manufacturing
      tier: production
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pharma-manufacturing-hpa
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    compliance: fda-21cfr11
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pharma-manufacturing-app
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: manufacturing_efficiency_percent
      target:
        type: AverageValue
        averageValue: "98"
  - type: Pods
    pods:
      metric:
        name: sensor_validation_success_rate
      target:
        type: AverageValue
        averageValue: "99.5"
  - type: Pods
    pods:
      metric:
        name: batch_integrity_score
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-logs-pvc
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    compliance: fda-21cfr11
  annotations:
    pharma.fda/retention-years: "7"
    pharma.fda/data-classification: "audit-trail"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: pharma-audit-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: batch-data-pvc
  namespace: pharma-prod
  labels:
    app: pharma-manufacturing
    compliance: fda-21cfr11
  annotations:
    pharma.fda/retention-years: "7"
    pharma.fda/data-classification: "batch-records"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: pharma-batch-storage
---
apiVersion: v1
kind: StorageClass
metadata:
  name: pharma-audit-storage
  labels:
    compliance: fda-21cfr11
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
  fsType: ext4
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: StorageClass
metadata:
  name: pharma-batch-storage
  labels:
    compliance: fda-21cfr11
parameters:
  type: gp3
  iops: "5000"
  throughput: "250"
  encrypted: "true"
  fsType: ext4
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true